name: portfolio.tokiodev.com deployment

on:
    push:
        branches: [main]
    
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Build
            run: npm run dev

    deploy-development:
        runs-on: ubuntu-latest
        environment: 
            name: development
            url: https://tokiodev.com
        needs: build
        steps:
            - name: Repo Checkout
              uses: actions/chekout@v1
            - name: Hostinger Deployment
              uses: easingthemes/ssh-deploy@main
              with:
                SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
                ARGS: "-rlgoDzvc --delete"
                SOURCE: "dist/"
                REMOTE_HOST: ${{vars.REMOTE_HOST}}
                REMOTE_USER: ${{vars.REMOTE_USER}}
                REMOTE_PORT: ${{vars.REMOTE_PORT}}
                TARGET: ./domains/tokiodev.com/public_html/